// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: SuppressMessage("Style", "IDE0300:Simplify collection initialization", Justification = "<auto-generated />", Scope = "NamespaceAndDescendants", Target = "~N:Dkw.Abp.OpenId.EntityFrameworkCore.PostgreSql.Migrations")]
[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "<auto-generated />", Scope = "NamespaceAndDescendants", Target = "~N:Dkw.Abp.OpenId.EntityFrameworkCore.PostgreSql.Migrations")]
[assembly: SuppressMessage("Roslynator", "RCS1021:Convert lambda expression body to expression body", Justification = "<auto-generated />", Scope = "NamespaceAndDescendants", Target = "~N:Dkw.Abp.OpenId.EntityFrameworkCore.PostgreSql.Migrations")]
