name: CD

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'DKW.Abp.sln'

    runs-on: ubuntu-22.04

    steps:

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.x
  
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.0
        
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with: 
        fetch-depth: 0

    - name: Restore dependencies
      run: nuget restore $SOLUTION
  
    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

    - name: Test
      run: dotnet test --configuration $BUILD_CONFIG --no-restore --no-build --verbosity normal

    - name: Publish
      if: startsWith(github.ref, 'refs/heads/main')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
